"""initial schema

Revision ID: 63a22ab9b244
Revises: 
Create Date: 2026-05-10 21:00:32.236485

"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '63a22ab9b244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_chats_telegram_id'))
    )
    op.create_index('ix_chats_tenant_active', 'chats', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_chats_tenant_id'), 'chats', ['tenant_id'], unique=False)
    op.create_table('outbox',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='outboxstatusenum'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index('ix_outbox_status_next', 'outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_table('publications',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('delivery_state', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications'))
    )
    op.create_index('ix_pub_hash', 'publications', ['content_hash'], unique=False)
    op.create_index('ix_pub_source_external', 'publications', ['source_id', 'external_id'], unique=True)
    op.create_index(op.f('ix_publications_source_id'), 'publications', ['source_id'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RSS', 'CITY', 'GOVERNMENT', name='sourcetypeenum'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('parser', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_type_active', 'sources', ['type', 'is_active'], unique=False)
    op.create_table('subscriptions',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tariff', sa.Enum('NEWS', 'CITY', 'DIASPORA', name='tariffenum'), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', name='subscriptionstateenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index('ix_subscriptions_chat_source', 'subscriptions', ['chat_id', 'source_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('source_health',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_health_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_source_health'))
    )
    op.create_table('topics',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('telegram_thread_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_topics_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_index('ix_topics_chat_thread', 'topics', ['chat_id', 'telegram_thread_id'], unique=True)
    op.create_index(op.f('ix_topics_tenant_id'), 'topics', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_tenant_id'), table_name='topics')
    op.drop_index('ix_topics_chat_thread', table_name='topics')
    op.drop_table('topics')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_chat_source', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_sources_type_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_publications_source_id'), table_name='publications')
    op.drop_index('ix_pub_source_external', table_name='publications')
    op.drop_index('ix_pub_hash', table_name='publications')
    op.drop_table('publications')
    op.drop_index('ix_outbox_status_next', table_name='outbox')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_chats_tenant_id'), table_name='chats')
    op.drop_index('ix_chats_tenant_active', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
