from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class LoggerProtocol(Protocol):
    def info(self, event: str, **kwargs: Any) -> None: ...
    def warning(self, event: str, **kwargs: Any) -> None: ...
    def error(self, event: str, **kwargs: Any) -> None: ...
    def debug(self, event: str, **kwargs: Any) -> None: ...


@runtime_checkable
class ConfigProtocol(Protocol):
    def get(self, key: str) -> Any: ...
