from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class LoggerProtocol(Protocol):
    def bind(self, **kwargs: Any) -> "LoggerProtocol": ...
    def unbind(self, *keys: str) -> "LoggerProtocol": ...
    def new(self, **kwargs: Any) -> "LoggerProtocol": ...

    def info(self, event: str, **kwargs: Any) -> None: ...
    def warning(self, event: str, **kwargs: Any) -> None: ...
    def error(self, event: str, **kwargs: Any) -> None: ...
    def debug(self, event: str, **kwargs: Any) -> None: ...
    def exception(self, event: str, **kwargs: Any) -> None: ...


@runtime_checkable
class ConfigProtocol(Protocol):
    ...
